// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TorGames.Database;

#nullable disable

namespace TorGames.Database.Migrations
{
    [DbContext(typeof(TorGamesDbContext))]
    [Migration("20251130000000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0-preview.6.25314.1");

            modelBuilder.Entity("TorGames.Database.Entities.Client", b =>
                {
                    b.Property<string>("ClientId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<int>("CpuCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFlagged")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTestMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUacEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastIpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("OsArchitecture")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("OsVersion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalConnections")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalMemoryBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("ClientId");

                    b.HasIndex("CountryCode");

                    b.HasIndex("IsBlocked");

                    b.HasIndex("IsFlagged");

                    b.HasIndex("LastSeenAt");

                    b.HasIndex("MachineName");

                    b.HasIndex("Username");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("TorGames.Database.Entities.ClientConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisconnectReason")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DisconnectedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ConnectedAt");

                    b.HasIndex("IpAddress");

                    b.ToTable("ClientConnections");
                });

            modelBuilder.Entity("TorGames.Database.Entities.CommandLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("InitiatorIp")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBroadcast")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultOutput")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResultReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WasDelivered")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CommandId");

                    b.HasIndex("CommandType");

                    b.HasIndex("SentAt");

                    b.ToTable("CommandLogs");
                });

            modelBuilder.Entity("TorGames.Database.Entities.ClientConnection", b =>
                {
                    b.HasOne("TorGames.Database.Entities.Client", "Client")
                        .WithMany("Connections")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("TorGames.Database.Entities.CommandLog", b =>
                {
                    b.HasOne("TorGames.Database.Entities.Client", "Client")
                        .WithMany("Commands")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");
                });

            modelBuilder.Entity("TorGames.Database.Entities.Client", b =>
                {
                    b.Navigation("Commands");

                    b.Navigation("Connections");
                });
#pragma warning restore 612, 618
        }
    }
}
